"""add_broadcasts_tables

Revision ID: 70c2d98dba91
Revises: 3a8f2b54a9c1
Create Date: 2025-05-07 22:50:44.440249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c2d98dba91'
down_revision: Union[str, None] = '3a8f2b54a9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('button_text', sa.String(length=100), nullable=True),
    sa.Column('button_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_users', sa.Integer(), nullable=True),
    sa.Column('received_count', sa.Integer(), nullable=True),
    sa.Column('button_clicks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broadcast_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('received', sa.Boolean(), nullable=True),
    sa.Column('clicked', sa.Boolean(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('donations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('menu_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('menu_items', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_order_items_menu_item_id', table_name='order_items')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_index('ix_orders_restaurant_id', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_user_id', table_name='orders')
    op.alter_column('restaurants', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('restaurants', 'invite_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('users', 'is_restaurant_owner',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_restaurant_owner',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('restaurants', 'invite_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('restaurants', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_restaurant_id', 'orders', ['restaurant_id'], unique=False)
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_order_items_menu_item_id', 'order_items', ['menu_item_id'], unique=False)
    op.alter_column('menu_items', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('donations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('broadcast_recipients')
    op.drop_table('broadcasts')
    # ### end Alembic commands ### 